name = "Suindara"
uuid = "7d6c9830-4b2a-4614-89ee-95a68c6f7e18"
version = "0.2.0"
authors = ["manelsen <emanuelmoura@gmail.com>"]

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[compat]
DBInterface = "2.6.1"
HTTP = "1.10.19"
JET = "0.11.3"
JSON3 = "1.14.3"
SQLite = "1.8.0"
